services:
  - type: web
    name: infohub-server
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: infohub-client
    rootDir: client
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    runtime: static
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_BASE
        value: ""
