services:
  - type: web
    name: infohub-server
    env: node
    rootDir: server
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3001

  - type: static
    name: infohub-client
    rootDir: client
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_API_BASE
        value: ""
